# Generated by Django 3.0.7 on 2021-09-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('unit_measure', models.CharField(max_length=50)),
                ('qty_prop_card', models.CharField(max_length=50)),
                ('qty_phy_count', models.CharField(max_length=50)),
                ('date_acquired', models.CharField(max_length=50)),
                ('end_user', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=50)),
                ('asset_image', models.ImageField(upload_to='asset/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('component_image', models.ImageField(upload_to='component/images/')),
            ],
        ),
    ]
