# Generated by Django 3.0.7 on 2022-03-28 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ict_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('property_num', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('serial_num', models.CharField(blank=True, max_length=50)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_acquired', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('serviceable', 'serviceable'), ('unserviceable', 'unserviceable'), ('no longer needed', 'no longer needed')], default='serviceable', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='asset/images/')),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('property_num', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('serial_num', models.CharField(blank=True, max_length=50)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_acquired', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('serviceable', 'serviceable'), ('unserviceable', 'unserviceable'), ('no longer needed', 'no longer needed')], default='serviceable', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='component/images/')),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ict_inventory.Asset')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ict_inventory.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ict_inventory.Brand'),
        ),
        migrations.AddField(
            model_name='asset',
            name='end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ict_inventory.EndUser'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ict_inventory.Location'),
        ),
    ]
