# Generated by Django 3.0.7 on 2021-09-25 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ict_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='component_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='component',
            name='date_acquired',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_acquired',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='qty_phy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='qty_prop_card',
            field=models.IntegerField(default=0),
        ),
    ]
