# Generated by Django 3.0.7 on 2021-09-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_inventory', '0002_auto_20210925_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_acquired',
            field=models.DateField(),
        ),
    ]
