# Generated by Django 3.0.7 on 2022-04-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_inventory', '0002_auto_20220328_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
