# Generated by Django 3.0.7 on 2022-06-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_inventory', '0006_auto_20220517_2218'),
    ]

    operations = [
    ]
