# Generated by Django 3.0.7 on 2023-12-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingRIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risNo', models.CharField(max_length=11, unique=True)),
                ('iarNo', models.CharField(max_length=11, unique=True)),
                ('dateOfDelivery', models.DateField()),
                ('supplier', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('stockNo', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('itemDescription', models.TextField()),
                ('qty', models.CharField(max_length=7)),
                ('remarks', models.TextField()),
                ('date_inspected', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ris',
            },
        ),
    ]
