# Generated by Django 3.0.7 on 2023-12-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedDIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iar_no', models.CharField(max_length=11, unique=True)),
                ('inspection_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateField()),
                ('purpose', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Completed DIA',
            },
        ),
        migrations.AlterModelOptions(
            name='issuingris',
            options={'verbose_name_plural': 'Issuing RIS'},
        ),
        migrations.RenameField(
            model_name='issuingris',
            old_name='dateOfDelivery',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='issuingris',
            old_name='itemDescription',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='issuingris',
            old_name='iarNo',
            new_name='ris_no',
        ),
        migrations.RenameField(
            model_name='issuingris',
            old_name='stockNo',
            new_name='stock_no',
        ),
        migrations.RemoveField(
            model_name='issuingris',
            name='date_inspected',
        ),
        migrations.RemoveField(
            model_name='issuingris',
            name='risNo',
        ),
    ]
