# Generated by Django 3.0.7 on 2023-12-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risgen', '0002_auto_20231212_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeddia',
            name='inspection_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='issuingris',
            name='stock_no',
            field=models.IntegerField(null=True),
        ),
    ]
