# Generated by Django 3.0.7 on 2023-12-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risgen', '0003_auto_20231217_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeddia',
            name='with_ris_no',
            field=models.BooleanField(default=False),
        ),
    ]
