# Generated by Django 3.0.7 on 2023-12-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risgen', '0005_auto_20231223_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuingris',
            name='supplier',
        ),
    ]
