# Generated by Django 3.0.7 on 2021-10-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='inspected',
        ),
    ]
