# Generated by Django 3.2.8 on 2021-10-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_inspection', '0002_remove_delivery_inspected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='image',
            field=models.ImageField(blank=True, upload_to='delivery_inspection/images/%Y/%m'),
        ),
    ]
