# Generated by Django 3.0.7 on 2023-01-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_inspection', '0004_partialdelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partialdelivery',
            options={'verbose_name_plural': 'partial deliveries'},
        ),
    ]
