# Generated by Django 3.0.7 on 2023-01-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_inspection', '0005_auto_20230130_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='inspector',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
