# Generated by Django 3.0.7 on 2023-02-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_inspection', '0006_delivery_inspector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='inspector',
        ),
    ]
