# Generated by Django 3.0.7 on 2023-02-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_inspection', '0007_remove_delivery_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='inspector',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
