# Generated by Django 3.0.7 on 2023-12-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_inspection', '0008_delivery_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deliverable',
            field=models.IntegerField(default=1),
        ),
    ]
