# Generated by Django 3.0.7 on 2023-01-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ictinv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ictinv.EndUser'),
        ),
        migrations.AddField(
            model_name='component',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ictinv.Location'),
        ),
    ]
