# Generated by Django 3.0.7 on 2023-01-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ictinv', '0002_auto_20230130_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ictinv.Asset'),
        ),
    ]
