# Generated by Django 3.0.7 on 2023-02-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ictinv', '0004_auto_20230220_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
